import {aiStatus} from './integrations.mjs';
import {complianceAction,parsePdf,complianceReport} from './compliance-api.mjs';
import {seed,transition,ROLES,addAudit,stamp} from '../lib/model.ts';
import {reportHtml} from './report.mjs';
import {createHash,randomBytes} from 'node:crypto';
const err=m=>{throw new Error(m)};
const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
const json=(data,status=200,extra={})=>Response.json(data,{status,headers:{...headers,...extra}});
const clean=s=>{const c=structuredClone(s);for(const t of c.tenders)if(!t.reviewed)for(const b of t.bids)b.quote=0;for(const a of c.audit)if(c.tenders.some(t=>t.id===a.tender&&!t.reviewed)){try{const p=JSON.parse(a.detail);if('quote' in p)p.quote='SEALED';a.detail=JSON.stringify(p)}catch{}}return c};
export function createApi(store){let initialized;async function init(){if(!initialized)initialized=store.init().catch(e=>{initialized=null;throw e});await initialized}
async function load(owner){const rows=await store.query('SELECT body,revision FROM workspaces WHERE owner = ?',[owner]);if(!rows[0])err('Workspace not found. Start a new demo session.');return {state:JSON.parse(rows[0].body),revision:rows[0].revision}}
async function save(owner,state,revision){const rows=await store.query('UPDATE workspaces SET body = ?,revision = revision + 1 WHERE owner = ? AND revision = ? RETURNING revision',[JSON.stringify(state),owner,revision]);if(!rows.length)err('Another action changed the workspace. Refresh and try again.');return revision+1}
return async function handle(req){try{await init();const url=new URL(req.url);const path=url.pathname.replace(/^\/\.netlify\/functions\/api/,'/api');if(req.method!=='GET'){const o=req.headers.get('origin');if(o&&o!==url.origin)err('Cross-origin changes are blocked.')}
const token=req.headers.get('cookie')?.match(/(?:^|;\s*)govbid_session=([^;]+)/)?.[1];const sessions=token?await store.query('SELECT owner,role FROM demo_sessions WHERE id = ? AND expires > ?',[token,Date.now()]):[];const session=sessions[0];
if(path==='/api/session'&&req.method==='POST'){const p=await req.json();if(!ROLES.includes(p.role))err('Choose a supported human demo role.');const owner=session?.owner??randomBytes(24).toString('hex');if(!session)await store.query('INSERT INTO workspaces (owner,body,revision) VALUES (?,?,0)',[owner,JSON.stringify(seed())]);const key=randomBytes(32).toString('hex');await store.query('INSERT INTO demo_sessions (id,owner,role,expires) VALUES (?,?,?,?)',[key,owner,p.role,Date.now()+30*86400000]);if(token)await store.query('DELETE FROM demo_sessions WHERE id = ?',[token]);const d=await load(owner);addAudit(d.state,p.role,'Demo role sign-in','WORKSPACE','Role permissions demonstration; not government identity verification.');await save(owner,d.state,d.revision);return json({ok:true},200,{'Set-Cookie':`govbid_session=${key}; HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000${url.protocol==='https:'?'; Secure':''}`})}
if(!session)return json({error:'DEMO_SESSION_REQUIRED'},403);
if(path==='/api/session'&&req.method==='DELETE'){await store.query('DELETE FROM demo_sessions WHERE id = ?',[token]);return json({ok:true},200,{'Set-Cookie':'govbid_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'})}
const {owner,role}=session;const d=await load(owner);let changed=false;for(const t of d.state.tenders)if(t.status==='Receiving bids'&&Date.parse(t.deadline)<=Date.now()){t.status='Bids locked';addAudit(d.state,'SYSTEM','Deadline reached',t.id,'Submission window automatically locked.');changed=true}if(changed)d.revision=await save(owner,d.state,d.revision);
const output=()=>json({state:clean(d.state),revision:d.revision,role,database:store.name});
if(path==='/api/compliance'&&req.method==='POST'){const p=await req.json();if(p.revision!==d.revision)err('Workspace changed. Refresh before saving.');await complianceAction(d.state,role,p);d.revision=await save(owner,d.state,d.revision);return output()}
if(path==='/api/compliance/report'&&req.method==='GET'){const t=d.state.tenders.find(t=>t.id===url.searchParams.get('id'));const b=t?.bids.find(b=>b.id===url.searchParams.get('bidId'));if(!b)err('Bidder not found.');return new Response(complianceReport(t,b),{headers:{...headers,'Content-Type':'text/html; charset=utf-8'}})}
if(path==='/api/compliance/parse'&&req.method==='POST'){if(!['PROCUREMENT_OFFICER','TECHNICAL_EVALUATOR','SUPER_ADMIN'].includes(role))err('Officer or evaluator role required.');const f=(await req.formData()).get('file');if(!(f instanceof File)||f.size>3*1024*1024||!f.size)err('Upload a PDF up to 3 MB.');const bytes=Buffer.from(await f.arrayBuffer());if(bytes.subarray(0,5).toString()!=='%PDF-')err('Invalid PDF.');return json(await parsePdf(bytes))}
if(path==='/api/workspace'&&req.method==='GET')return output();
if(path==='/api/workspace'&&req.method==='POST'){const p=await req.json();if(p.revision!==d.revision)err('The workspace changed. Refresh before saving.');const id=transition(d.state,role,p.action,p.payload??{});d.revision=await save(owner,d.state,d.revision);return json({state:clean(d.state),revision:d.revision,role,id})}
if(path==='/api/import'&&req.method==='POST'){if(!['PROCUREMENT_OFFICER','SUPER_ADMIN'].includes(role))err('Procurement officer role required.');const p=await req.json();if(!Array.isArray(p.rows)||!p.rows.length||p.rows.length>50)err('Import between 1 and 50 records.');if(!p.source||typeof p.source!=='string')err('Record the dataset source.');const ids=[];for(const row of p.rows){const id=transition(d.state,role,'create',{title:row.title,department:row.department,category:row.category||'Imported procurement',description:(row.description||row.title)+'\nSource: '+p.source,value:Math.round(Number(row.value_crore)*1e9),deadline:row.deadline,opening:row.opening});ids.push(id)}addAudit(d.state,role,'Dataset imported','WORKSPACE',ids.length+' drafts from '+p.source+'; not AI verified.');d.revision=await save(owner,d.state,d.revision);return output()}
if(['/api/documents','/api/compliance/source'].includes(path)&&req.method==='POST'){if(!(path==='/api/compliance/source'?['PROCUREMENT_OFFICER','TECHNICAL_EVALUATOR','SUPER_ADMIN']:['PROCUREMENT_OFFICER','SUPER_ADMIN']).includes(role))err('Procurement officer role required.');const form=await req.formData();const t=d.state.tenders.find(t=>t.id===form.get('id'));if(!t||(path==='/api/compliance/source'?['Approved','Rejected'].includes(t.status):!['Draft','Receiving bids'].includes(t.status)))err('Document submission is locked.');if(path==='/api/compliance/source'&&!t.bids.some(b=>b.id===form.get('bidId')))err('Bidder not found.');const file=form.get('file');if(!(file instanceof File)||!file.size||file.size>3*1024*1024)err('Choose a non-empty file up to 3 MB.');const ext=file.name.split('.').pop().toLowerCase();const types={pdf:['application/pdf'],docx:['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],xlsx:['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],csv:['text/csv','application/vnd.ms-excel'],png:['image/png'],jpg:['image/jpeg'],jpeg:['image/jpeg'],txt:['text/plain']};if(!types[ext]?.includes(file.type))err('Unsupported file type or MIME mismatch.');const data=Buffer.from(await file.arrayBuffer());if(ext==='pdf'&&data.subarray(0,5).toString()!=='%PDF-')err('File does not have a valid PDF header.');const id=randomBytes(16).toString('hex');const hash=createHash('sha256').update(data).digest('hex');await store.query('INSERT INTO documents (id,owner,name,mime,content) VALUES (?,?,?,?,?)',[id,owner,file.name.slice(0,180),file.type,data.toString('base64')]);t.documents.push({id,name:file.name.slice(0,180),kind:path==='/api/compliance/source'?'Statutory evidence':'Supporting document',bidId:form.get('bidId')||undefined,size:file.size,hash,date:stamp(),mock:false});addAudit(d.state,role,'Document uploaded',t.id,file.name+' · SHA-256 '+hash+' · Original retained; extraction evidence recorded separately.');try{d.revision=await save(owner,d.state,d.revision)}catch(e){await store.query('DELETE FROM documents WHERE id = ? AND owner = ?',[id,owner]);throw e}return output()}
if(path==='/api/documents'&&req.method==='GET'){const id=url.searchParams.get('id');const docs=await store.query('SELECT name,mime,content FROM documents WHERE id = ? AND owner = ?',[id,owner]);if(!docs[0])err('Document not found. Sample documents have previews only.');addAudit(d.state,role,'Document downloaded','WORKSPACE',docs[0].name);await save(owner,d.state,d.revision);return new Response(Buffer.from(docs[0].content,'base64'),{headers:{...headers,'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(docs[0].name)}`}})}
if(path==='/api/report'&&req.method==='GET'){const t=d.state.tenders.find(t=>t.id===url.searchParams.get('id'));if(!t?.reportAt)err('Generate the report first.');return new Response(reportHtml(t,d.state),{headers:{...headers,'Content-Type':'text/html; charset=utf-8',...(url.searchParams.has('download')?{'Content-Disposition':'attachment; filename="GovBid-evaluation-report.html"'}:{})}})}
if(path==='/api/integrations')return json({ai:aiStatus(),registry:'Mock and imported records; no live government connection'});
if(path==='/api/health')return json({database:store.name,connected:true,tenders:d.state.tenders.length});
return json({error:'Endpoint not found'},404)
}catch(e){console.error('GovBid request failed:',e.message);return json({error:e.message?.includes('relation')?'Database schema is unavailable. Apply database/schema.sql and retry.':e.message||'Request failed. Please retry.'},400)}}}

