import {createServer} from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {readFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {createApi} from './api.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));await mkdir(path.join(root,'data'),{recursive:true});const database=new DatabaseSync(path.join(root,'data/govbid.sqlite'));database.exec('PRAGMA journal_mode=WAL');database.exec(await readFile(path.join(root,'database/schema.sql'),'utf8'));
const api=createApi({name:'SQLite · local file',init:async()=>{},query:async(sql,p=[])=>{const st=database.prepare(sql);return /^\s*SELECT|RETURNING/i.test(sql)?st.all(...p):(st.run(...p),[])}});
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1:4173');if(url.pathname.startsWith('/api/')){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>5*1024*1024)throw Error('Request exceeds 5 MB.');chunks.push(c)}const response=await api(new Request(url,{method:req.method,headers:req.headers,body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)}));res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));return}const requested=path.resolve(root,'dist','.'+decodeURIComponent(url.pathname));if(!requested.startsWith(path.resolve(root,'dist')+path.sep)&&requested!==path.resolve(root,'dist'))throw Error('Invalid path');let file;let name=requested;try{file=await readFile(requested)}catch{name=path.join(root,'dist/index.html');file=await readFile(name)}const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.json':'application/json','.webmanifest':'application/manifest+json'};res.writeHead(200,{'Content-Type':mime[path.extname(name)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});res.end(file)}catch(e){res.writeHead(500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}))}});server.listen(4173,'127.0.0.1',()=>console.log('GovBid AI: http://127.0.0.1:4173 — SQLite database: data/govbid.sqlite'));
